backend:
  name: github
  repo: RiverviewFarm/riverviewfarm-v2
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://riverviewfarm.ca/"

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: /
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: "image" }
      - { name: images, label: Images, widget: "list", field: {label: Image, name: image, widget: image}}
      - { name: video, label: "YouTube URL", widget: "string" }
      - { name: location, label: "Google Maps Location Link", widget: "string" }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }